# Jekyll config file
remote_theme: deargle/retlab
# theme: retlab

title: Dave Eargle
tagline: Information Systems Management Researcher
description: Personal website of David Eargle, Information Systems Management Researcher
author: David Eargle

github_username: deargle
pgp_key: 3DE8 E078 BDB7 C6E6 EDFA 2829 E96E 4A42 8DC0 1F3A
google_scholar: https://scholar.google.com/citations?user=Nw7ibigAAAAJ&hl=en
orcid: https://orcid.org/0000-0002-4056-8114
stackoverflow: https://stackoverflow.com/users/1396649/deargle

twitter:
  username: DavidEargle
  card: summary

# seo
social:
  name: Dave Eargle
  links:
    - https://orcid.org/0000-0002-4056-8114
    - https://stackoverflow.com/users/1396649/deargle
    - https://scholar.google.com/citations?user=Nw7ibigAAAAJ&hl=en
    - https://github.com/deargle
    - https://twitter.com/DavidEargle
    - https://linkedin.com/in/dave-eargle-097a2925/


lang: en-US

nav_pages:
    - index.md
    - vita.md
    - classes/index.md
    - projects.md
    - about.md
    - contact.md

footer_pages:
    - fine-print.md

contact_links:
   - name: Twitter
     url: https://twitter.com/DavidEargle
     icon: twitter
   - name: GitHub
     url: https://github.com/deargle
     icon: github

url: 'https://daveeargle.com'
repository: 'deargle/deargle.github.io'

ga_username: 'UA-35065822-1'

# JSON-LD
email: dave@daveeargle.com
gender: male
employer:
  name: CU Boulder
  url: https://www.colorado.edu/business/david-eargle
job_title: Assistant Professor, Organizational Leadership and Information Analytics

# Collections
collections:
    classes:
        output: true
    class_summaries: # This exists because this repo currently has classes within it which I'll eventually move out into their own repos.
    schools:
    projects:

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - test
  - less
  - scss
  - media
  - feature-detects
  - composer.json
  - component.json
  - grunt.js
  - assets/vendor/jquery/src
  - assets/vendor/bootstrap-sass/assets/fonts
  - assets/vendor/bootstrap-sass/assets/stylesheets
  - assets/vendor/bootstrap-sass/assets/javascripts/bootstrap/
  - ".bundle"
  - vendor
  - node_modules
  - Rakefile
  - "*.Rmd"
  - R
  - yarn.lock
  - yarn-error.log


#number of items in RSS feed
feed:
  path: "/feed.xml"
  posts_limit: 10
  categories:
    - professional
    - unprofessional


#permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
        path: ""
        type: "classes"
    values:
        layout: "syllabus"

# Plugins
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 syntax_highlighter: rogue
 syntax_highlighter_opts:
    guess_lang: true

highlighter: rouge
gist:
    noscript: false
future: true

host: localhost
port: 3000
